use product

create table stringdata(string varchar(10),number int)
insert into stringdata values('A',50),('B',10),('A',20),('B',10),('C',20),('D',10),('D',10),('C',20),('E',10)
SELECT * FROM stringdata

SELECT STRING,SUM(number)TOTAL FROM stringdata
GROUP BY STRING

SELECT STRING+ CAST(SUM(NUMBER) AS VARCHAR)TOTAL FROM stringdata GROUP BY STRING 

CREATE TABLE GROCERIES(ITEMNAME VARCHAR(20),COST INT)
INSERT INTO GROCERIES VALUES('POTATO',20),('BANANA',10),('CABAGE',50),('MANGO',60)

SELECT * FROM GROCERIES

 WITH CTE1
 AS
 (
 SELECT ITEMNAME,COST ,CASE 
    WHEN ITEMNAME IN ('BANANA','MANGO') THEN 'FRUIT'
	WHEN ITEMNAME IN ('POTATO','CABAGE') THEN 'VEGETABLE'
	ELSE 'NONE'
	END  AS GTYPE
	FROM GROCERIES
)
SELECT GTYPE,SUM(COST) TOTALCOST
FROM CTE1 
GROUP BY GTYPE	


SELECT A.G_TYPE,SUM(A.COST)TOTAL_COST
    FROM ( SELECT ITEMNAME,
	CASE 
    WHEN ITEMNAME IN ('BANANA','MANGO') THEN 'FRUITS'
	 WHEN ITEMNAME IN ('POTATO','CABAGE') THEN 'VEGETABLES'
	 END  G_TYPE,COST
	FROM GROCERIES)AS A
	GROUP BY A.G_TYPE








CREATE TABLE STRINGDATA1(STRING VARCHAR(10))
INSERT INTO STRINGDATA1 VALUES('A50'),('B10'),('A20'),('B10'),('C20'),('D10'),('D10'),('C20'),('C10')

SELECT * FROM STRINGDATA1
 UPDATE STRINGDATA1 SET STRING='C15' WHERE STRING='C10'
SELECT LEFT(STRING,1) AS STRING,SUM(CAST(RIGHT(STRING,2) AS INT))AS TOTAL FROM STRINGDATA1 GROUP BY LEFT(STRING,1)

CREATE TABLE STRING2(STRING VARCHAR(10))
INSERT INTO STRING2 VALUES('A 50 C'),('B 10'),('A20'),('B10'),('C 2 0 '),('D10'),('D10'),('C20'),('C10')

SELECT LEN(STRING)-LEN(REPLACE(STRING,' ',''))AS TOTALSPACECOUNT FROM STRING2



SELECT LEN('ASSERTIVE')AS LENGTHS
SELECT DATALENGTH('  ASSERTIVE  ')AS COUNTSPACE
SELECT LEN('ASSERTIVE') - LEN(REPLACE('ASSERTIVE', 'AEIOU', ''))

SELECT TRANSLATE('QWERTY','Q',' ')
SELECT REPLACE('QWERTY','WE','UR')
SELECT STUFF('QWERTY',2,3,'AS')
SELECT STUFF('SQL CLASS',1,3,'HTML')
SELECT STUFF('SQL CLASS',1,3,'HTTP')
SELECT STUFF('SQL CLASS',1,2,'TCP')

SELECT STUFF('SQL CLASS SQL SOLUTION SQL TUTORIAL',1,3,'HTML')
SELECT REPLACE('SQL CLASS SQL SOLUTION SQL TUTORIAL','SQL','HTML')

--GOTHROUGH THE TOPIC IN SUBSTRING,LEN,CHARINDEX AND LEFT AND RIGHT
--1.HOW TO REMOVE THE VOWELS IN A GIVEN STRING
select TRANSLATE('assertive','aeiou','     ')
select TRANSLATE(ename,'aeiou','     ')vowelsremoved from empdup


--2.INITIAL IS CAPITAL LEFT IS SMALL
select upper(substring(ename,1,1))+lower(SUBSTRING(ename,2,len(ename))) as caps from empdup

SELECT UPPER(LEFT(ENAME,1))+LOWER(SUBSTRING(ENAME,2,LEN(ENAME))) AS NAMES FROM EMPDUP

--3.ID , NAME
--  1		AMIT
--  1		KIRAN
--  2     GAGAN
--  2     TANU
--  2     TEJA
CREATE TABLE NAMEWISE(ID INT,NAME VARCHAR(20))
INSERT INTO NAMEWISE VALUES (1,'AMIT'),(1,'KIRAN'),(2,'GAGAN'),(2,'TEJA')
INSERT INTO NAMEWISE VALUES(3,NULL),(3,'KUMAR')

SELECT ID,STRING_AGG(NAME,',')CONCATINATED_NAME 
FROM NAMEWISE
GROUP BY ID


SELECT ID,CONCAT(NAME,',') FROM NAMEWISE
SELECT ID,CONCAT_WS(',',NAME,ID) FROM NAMEWISE

--O/P
-- ID  NAME 
-- 1   AMIT,KIRAN
-- 2   GAGAN,TANU,TEJA









SELECT * FROM EMPDUP

SELECT CONCAT(EMPNO,ENAME)AS CONCA FROM EMPDUP
SELECT 

DECLARE @CONSONENT INT =0
DECLARE @V_STR varchar(10)='WRTYP',
@I INT=1,
@V_COUNT INT=0
BEGIN
WHILE @I<=LEN(@V_STR)
BEGIN
IF SUBSTRING(@V_STR,@I,1) IN('A','E','I','O','U')
BEGIN
SET @V_COUNT=@V_COUNT+1
END
ELSE
BEGIN
  SET @CONSONENT=@CONSONENT+1
  END
  SET @I=@I+1
END 
PRINT @V_STR
PRINT @V_COUNT
PRINT @CONSONENT
END

