 select * from emp
 select * from dept

 with cte_empcount(deptno,totalemployees)
 as
 (
  select deptno,count(*)as totalemployees from emp group by deptno 
 )
 select DEPT.deptno,dname,totalemployees FROM cte_empcount JOIN dept ON cte_empcount.DEPTNO=DEPT.deptno
 ORDER BY totalemployees

 WITH EMPCOUNT_ACC_RESEARCH(DNAME,TOTALEMP)
 AS
 (
 SELECT DNAME,COUNT(EMPNO) AS TOTALEMP FROM EMP EM
 JOIN DEPT ON EM.deptno=DEPT.deptno
 WHERE DNAME IN('ACCOUNTING','RESEARCH')
 GROUP BY dname
 ),
 EMPCOUNT_SALES_OPERATIONS(DNAME,TOTALEMP)
 AS
 (
 SELECT DNAME,COUNT(EMPNO)AS TOTALEMP FROM EMP E2
 JOIN DEPT 
 ON E2.deptno=DEPT.deptno
 WHERE DNAME IN ('SALES','OPERATIONS')
 GROUP BY dname
 )
 SELECT * FROM EMPCOUNT_ACC_RESEARCH
 UNION ALL
 SELECT * FROM EMPCOUNT_SALES_OPERATIONS

 --- RETURN MONDAY TO SATURDAY --

 WITH CTE_WEEKDAY(N,WEEKDAYS)
 AS
 (
 SELECT 0, DATENAME(WEEKDAY,0)
 UNION ALL
 SELECT N+1,DATENAME(WEEKDAY,N+1)
 FROM CTE_WEEKDAY
 WHERE N<6
 )
 SELECT WEEKDAYS FROM CTE_WEEKDAY


 WITH CTE_EMPL
 AS
 ( 
   SELECT* FROM emp WHERE SAL>2000
 )
 SELECT * FROM CTE_EMPL

 WITH CTE_AVG
 AS
 (
   SELECT AVG(SAL) AS AVG_SAL FROM emp 
   GROUP BY deptno
 )

 SELECT * FROM CTE_AVG A,EMP B
 WHERE A.AVG_SAL<B.sal



 SELECT *,(SELECT AVG(SAL) AS AVG_SAL FROM EMP) AS AVE_SAL FROM emp


 WITH CTE_SALA
 AS
 (
  SELECT *,AVG(SAL) OVER() AS A FROM emp
 )
 SELECT * FROM CTE_SALA WHERE SAL>A


 CREATE TABLE DUPLICATE(ID INT)
INSERT INTO DUPLICATE VALUES(1),(1),(2),(2),(2),(3),(4)

SELECT * FROM DUPLICATE
 WITH CTE_DEL
 AS
(
   SELECT *,ROW_NUMBER() OVER(PARTITION BY ID ORDER BY ID) AS R FROM DUPLICATE
)
DELETE FROM CTE_DEL WHERE R>1



WITH CTE_NUM
AS
(
SELECT 1 AS N
UNION ALL
SELECT N+1 FROM CTE_NUM
WHERE N<200
)
SELECT * FROM CTE_NUM
OPTION (MAXRECURSION 200)


WITH CTE_DAYS(N,WEEKDAY)
AS
( SELECT 0,DATENAME(WEEKDAY,0)
UNION ALL
SELECT N+1,DATENAME(WEEKDAY,N) FROM CTE_DAYS
 WHERE N<6
)
SELECT * FROM CTE_DAYS

WITH CTE_DAYS(N,WEEKDAY)
AS
( SELECT 0,DATENAME(WEEKDAY,0)
UNION ALL
SELECT N+1,DATENAME(WEEKDAY,N+1) FROM CTE_DAYS
 WHERE N<6
)
SELECT * FROM CTE_DAYS